version: 2.1

orbs:
  ruby: circleci/ruby@2
  node: circleci/node@5
  browser-tools: circleci/browser-tools@1.1

jobs:
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.6-browsers
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: test-pguser
          POSTGRES_DB: sample-test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: test-pguser
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - browser-tools/install-chrome
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test # Run rspec in parallel

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
